### ISSUE TITLE
Compilation failure on MacOS with qhull 2012

### ISSUE THREAD

**Issue by smaret** [smaret/lime#30]
On MacOSX, the compilation fails with the following message:

```shell
% lime model.c 
gcc -O3 -falign-loops=16 -fno-strict-aliasing -DTEST -I/usr/include -I/usr/include/libqhull  -I/Users/smaret/Models/lime/include -I/Users/smaret/Models/lime/src -I/Users/smaret/include -I/opt/local/include -I/sw//include -o src/aux.o -c src/aux.c
gcc -O3 -falign-loops=16 -fno-strict-aliasing -DTEST -I/usr/include -I/usr/include/libqhull  -I/Users/smaret/Models/lime/include -I/Users/smaret/Models/lime/src -I/Users/smaret/include -I/opt/local/include -I/sw//include -o src/curses.o -c src/curses.c
gcc -O3 -falign-loops=16 -fno-strict-aliasing -DTEST -I/usr/include -I/usr/include/libqhull  -I/Users/smaret/Models/lime/include -I/Users/smaret/Models/lime/src -I/Users/smaret/include -I/opt/local/include -I/sw//include -o src/grid.o -c src/grid.c
src/grid.c:14:21: fatal error: qhull_a.h: No such file or directory
 #include <qhull_a.h>
                     ^
compilation terminated.
make: *** [src/grid.o] Error 1
rm -f *~ src/*.o lime.x  
```

Indeed, `qhull_a.h` is located in `/opt/local/include/libqhull`, but the compilation line has `-I/usr/include/libqhull`.

**Comment by smaret** [comment]
For reference, this bug was introduced in f50778a6cb42f6fc928 and 415a5047d4f2f68f15e858f7d, and it is also discussed in PR #29.

**Comment by smaret** [comment]
@imckstewart : do you want to fix this, or should I do it?

**Comment by allegroLeiden** [comment]
I'll give it a go.

**Comment by smaret** [comment]
Fixed with 6327c9860c86f58f9843d868b4a2562a63e2d5d1. Thanks @allegroLeiden!
